apiVersion: v1
kind: Service
metadata:
  name: books-play-k8-service
spec:
  type: NodePort   # for NodePort local deployemnt     # 'LoadBalancer' for cloud deployment
  selector:
    app: books-play-k8
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
